version: '3'
services:
  web:
    build: ./docker/php
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=boycott.dev
    volumes:
      - .:/codes/boycott
    depends_on:
      - db
  db:
    build: ./docker/mysql
    ports:
      - 3307:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
